name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run Cypress tests (UI + API)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          build: npm run report:merge
          start: ''
          wait-on: ''
          spec: |
            cypress/e2e/ui/**/*.cy.js
            cypress/e2e/api/**/*.cy.js
            cypress/e2e/bdd/**/*.feature

      - name: Merge Mochawesome JSON
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/mochawesome.json || true

      - name: Generate HTML report
        run: |
          npx marge cypress/reports/mochawesome.json -f index -o cypress/reports/html || true

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html
